// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloud-disk/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: refreshAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: CoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/mail/sendCode",
				Handler: SendCodeRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/user",
				Handler: RegisterUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/share/detail",
				Handler: ShareDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: FileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload/chunk",
					Handler: FileUploadChunkHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload/chunk/complete",
					Handler: FileUploadChunkCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload/prepare",
					Handler: fileUploadPrepareHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/delete",
					Handler: UserFileDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/file/move",
					Handler: userFileMoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/name/update",
					Handler: UserFileNameUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/save",
					Handler: shareSaveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/share",
					Handler: shareFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/folder/create",
					Handler: UserFolderCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/repo/list",
					Handler: UserRepoListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/repo/save",
					Handler: UserRepoSaveHandler(serverCtx),
				},
			}...,
		),
	)
}
